server:
  port: 2010
  error:
    include-message: always

spring:
  servlet:
    multipart:
      max-request-size: 30MB
      max-file-size: 16MB
  datasource:
    url: jdbc:postgresql://34.143.238.116:5432/travelmarketplace
    username: postgres
    password: capstonevlu
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
